CREATE TABLE IF NOT EXISTS USERS (
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	USERNAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
	TYPE INT NOT NULL CHECK(TYPE > 0 AND TYPE <= 3)
);

CREATE TABLE IF NOT EXISTS QUESTIONS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	Q_TEXT TEXT NOT NULL,
	STATE INT NOT NULL CHECK (STATE == 0 OR STATE == 1),
	TYPE INT NOT NULL,
	REQUIRED INT NOT NULL CHECK(REQUIRED == 0 OR REQUIRED == 1),
	RESPONSES BLOB NOT NULL
);

CREATE TABLE IF NOT EXISTS SURVEYS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	NAME TEXT NOT NULL,
    C_ID INT NOT NULL,
    STATE INT NOT NULL CHECK(STATE >= 0 AND STATE <= 2),
	QUESTIONS BLOB NOT NULL,
    FOREIGN KEY (C_ID) REFERENCES COURSES(ID)
);

CREATE TABLE IF NOT EXISTS RESPONSES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	U_ID INT NOT NULL,
    S_ID INT NOT NULL,
    RESPONSES BLOB NOT NULL,
	FOREIGN KEY (U_ID) REFERENCES USERS(ID),
	FOREIGN KEY (S_ID) REFERENCES SURVEYS(ID)
);

CREATE TABLE IF NOT EXISTS COURSES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    COURSE VARCHAR(10) NOT NULL,
    SESSION VARCHAR(5) NOT NULL
);

CREATE TABLE IF NOT EXISTS ENROLMENTS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    U_ID INT NOT NULL,
    C_ID INT NOT NULL,
    FOREIGN KEY (U_ID) REFERENCES USERS(ID),
    FOREIGN KEY (C_ID) REFERENCES COURSES(ID)
);
